/** fab_erp shared UI primitives — see DESIGN_SYSTEM.md §7. */
export { Surface } from './Surface';
export { GlassBar } from './GlassBar';
export { StatusBadge } from './StatusBadge';
export { Mono } from './Mono';
export { PageHeader } from './PageHeader';
export { StatStrip, type Stat } from './StatStrip';
export { FilterBar, FacetChip } from './FilterBar';
export { EntityList, EntityRow, type SortableField } from './EntityList';
export { EmptyState } from './EmptyState';
export { SkeletonBlock, ListSkeleton, StatSkeleton, DetailSkeleton, ChartSkeleton, CardGridSkeleton } from './Skeletons';
export { ToastProvider, useToast } from './Toast';
export { DetailLayout, CrossLink, FactItem, type DetailTab } from './DetailLayout';
export { TreeRow } from './TreeRow';
export { RunPanel, type RunState } from './RunPanel';
export { PipelineBoard, PipelineCard, type PipelineStage } from './PipelineBoard';
export { WorkQueueCard } from './WorkQueueCard';
export { SortableTableHead, type SortableColumn } from './SortableTableHead';
export { statusFamily, type StatusFamily } from '../statusMap';

// ── Elevation-plan primitives (FAB_ERP_UX_ELEVATION_PLAN.md §3.2) ──
export { DataTable, type DataColumn } from './DataTable';
export { FormDialog, ConfirmDialog } from './FormDialog';
export { backendMessage } from '../utils/backendMessage';
export { SideSheet } from './SideSheet';
export { SectionCard, StickyActionBar } from './SectionCard';
export { default as RawMaterialSelect } from './RawMaterialSelect';
export { CommandPaletteProvider } from './CommandPalette';
export { useCommandPalette } from './commandPaletteContext';
export { ShortcutsHelp } from './ShortcutsHelp';
export { useShortcutsHelp } from '../hooks/useShortcutsHelp';
export { NumberCell, QtyCell, DateCell } from './Cells';
export { ExceptionFeed, type ExceptionItem, type ExceptionSeverity } from './ExceptionFeed';
export { MarksPanel } from './MarksPanel';
export { CrewPanel } from './CrewPanel';
export { PersonSheet, shiftSpan, type ShiftOption } from './PersonSheet';
export { LeaveDialog } from './LeaveDialog';
export { GapTable } from './GapTable';
export { GapExcelBar } from './GapExcelBar';
export { MachineTabs } from './MachineTabs';
export { ExitWorkerDialog } from './ExitWorkerDialog';
export { AddPeopleDialog, type MachineOption } from './AddPeopleDialog';
export { LiveIndicator } from './LiveIndicator';
export { formatElapsed } from '../utils/formatElapsed';
export { useLiveRefresh, useNowTick, formatAge } from '../hooks/useLiveRefresh';
export { Heatstrip, HeatstripLegend, type HeatSegment, type RunState as HeatRunState } from './charts/Heatstrip';
export { BarChart, ChartCard, type BarDatum } from './charts/BarChart';
