export const STANDARD_UOMS = [
  { label: 'EA',    value: 'EA' },
  { label: 'PC',    value: 'PC' },
  { label: 'KG',    value: 'KG' },
  { label: 'G',     value: 'G' },
  { label: 'MG',    value: 'MG' },
  { label: 'TON',   value: 'TON' },
  { label: 'L',     value: 'L' },
  { label: 'ML',    value: 'ML' },
  { label: 'M',     value: 'M' },
  { label: 'CM',    value: 'CM' },
  { label: 'MM',    value: 'MM' },
  { label: 'M2',    value: 'M2' },
  { label: 'M3',    value: 'M3' },
  { label: 'BOX',   value: 'BOX' },
  { label: 'SET',   value: 'SET' },
  { label: 'PAIR',  value: 'PAIR' },
  { label: 'ROLL',  value: 'ROLL' },
  { label: 'SHEET', value: 'SHEET' },
  { label: 'PACK',  value: 'PACK' },
  { label: 'DZ',    value: 'DZ' },
];
